// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhcC6ksJX7hjBplPNdYqA9DzWEG17hsm4',
    appId: '1:665756281433:web:9b35865aa57e54ed3f5f48',
    messagingSenderId: '665756281433',
    projectId: 'deneme-3226d',
    authDomain: 'deneme-3226d.firebaseapp.com',
    storageBucket: 'deneme-3226d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWD9uaX3Rv6tDi7SbrvSwXB-qYn4ApMfU',
    appId: '1:665756281433:android:0685e1bd2eab02ae3f5f48',
    messagingSenderId: '665756281433',
    projectId: 'deneme-3226d',
    storageBucket: 'deneme-3226d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUZ16NLUNCXsB4zw8LAE2s_ubug4YgwEg',
    appId: '1:665756281433:ios:2419fb252347daca3f5f48',
    messagingSenderId: '665756281433',
    projectId: 'deneme-3226d',
    storageBucket: 'deneme-3226d.appspot.com',
    iosClientId: '665756281433-0dttea963b585ops0viaaahkpjligu0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUZ16NLUNCXsB4zw8LAE2s_ubug4YgwEg',
    appId: '1:665756281433:ios:2419fb252347daca3f5f48',
    messagingSenderId: '665756281433',
    projectId: 'deneme-3226d',
    storageBucket: 'deneme-3226d.appspot.com',
    iosClientId: '665756281433-0dttea963b585ops0viaaahkpjligu0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
